name: Python application test with github actions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      working_directory: ./cloud-computing-foundations/scaffold/

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        

      # Setup python version 3.8
      - name: Setup python version 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      
      # Install dependencies
      - name: Install dependencies
        run: |
          make install
        working_directory: ${{ env.working_directory }}

      # Lint with pylint
      - name: Lint with pylint
        run: |
          make lint
        working-directory: ${{ env.working_directory }}

      # Run tests
      - name: Test with pytest
        run: |
          make test
        working-directory: ${{ env.working_directory }}

      # Format code with python black
      - name: Format code with python black
        run: |
          make format
        working-directory: ${{ env.working_directory }}
